### ISSUE TITLE
getStringFromTemplate

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#1]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L58

В условии же явно написано, что надо использовать темплейты:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

**Comment by levyn** [comment]
Разобрался, на самом деле проще чем объединением строк. А тегированные шаблоны - вообще вещь!
