### ISSUE TITLE
getDistanceBetweenPoints

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#10]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/02-numbers-tasks.js#L83-L86

Замечательно, но у нас тренинг не по математике, а по javascript.
RTFM https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot

**Comment by levyn** [comment]
поправил
