### ISSUE TITLE
getLastDigit

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#11]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/02-numbers-tasks.js#L141-L142

Переводить число в строку и потом работать со строкой как минимум неэффективно. Любые операции с числами намного быстрее операций со строками.
RTFM https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder

**Comment by levyn** [comment]
a%10
