### ISSUE TITLE
toNumber

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#13]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/02-numbers-tasks.js#L249-L253

В таких случаях результат принято возвращать в виде тернарной операции
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

**Comment by levyn** [comment]
ok
