### ISSUE TITLE
timeSpanToString

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#15]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/03-date-tasks.js#L86-L91

Прямолинейное решение. Можно похитрее:
```
return new Date(endDate - startDate).toISOString().slice(...); 
```

**Comment by levyn** [comment]
готово
toISOString()
