### ISSUE TITLE
extractNameFromTemplate

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#2]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L72

Тут можно написать короче
```
return value.slice(7, -1);
```
slice довольно мощная функция с емкими аргументами, надо уметь этим пользоваться 

Таже проблема в unbracketTag:
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L148

**Comment by levyn** [comment]
Да, немного недочитал
