### ISSUE TITLE
getFirstChar

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#3]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L87

Строки почти во всех языках являются итерируемыми объектами, так что можно писать короче:
```
return value[0];
```

**Comment by levyn** [comment]
Знаем, у прототипов строк и объектов, массивов есть общие свойства.
