### ISSUE TITLE
removeLeadingAndTrailingWhitespaces

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#4]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L102

RTFM https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

В нчале модуля есть ссылки, достаточно прочитать и выучить все стандартные методы string, чтобы выполнять эти задания.

**Comment by levyn** [comment]
Поспешил, решил что нужны регулярные выражения
