### ISSUE TITLE
getRectangleString

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#5]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L204-L210

Куча переменных с бессмыленными названиями. Мне целую минуту понадобится, чтобы понять, что получиться для
```
var e=b+d+bb;
```

**Comment by levyn** [comment]
Переобозвал...
