### ISSUE TITLE
encodeToRot13

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#6]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L230-L249

Это задание на строки, а не на массивы. Все решение можно сделать одной функцией 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

Кроме того, в коде куча магических цифр 122, 65, 97, 90, 64, 77 и тд. Не завидую тому, кому понадобиться немного модифицировать этот код.
Все магические цифры нужно оформлять в виде констант с понятными именами:
```
  const lettersCount = 26;
  const lowercaseOffset = 'a'.charCodeAt(0);
  const uppercaseOffset = 'A'.charCodeAt(0);
  ...
```

**Comment by levyn** [comment]
Разобрался...
