### ISSUE TITLE
isString

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#7]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L266-L270

Обычно в таких случаях не используют `if`. Принято сразу писать
```
return <условие>
```
где <условие> формируется с помощью https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators

**Comment by levyn** [comment]
Сократил
