### ISSUE TITLE
getCardId

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#8]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/01-strings-tasks.js#L299-L303

Идея хорошая, но решение очень прямолинейное.
Можно сделать похитрее:
```
return '♣♦♥♠'.indexOf(value.slice(-1)) * 13 + ...
```

**Comment by levyn** [comment]
Даже и не подумал о таком варианте. 
В зависимости от условий задачи еще можно по ASCII символам вычислять - но код больше получиться.
