### ISSUE TITLE
getAverage

### ISSUE THREAD

**Issue by aorgish** [levyn/rolling-scopes-js-assignments#9]
https://github.com/levyn/rolling-scopes-js-assignments/blob/c2d18d00da7b38ce8a87c382be624cd15441b502/task/02-numbers-tasks.js#L57-L64

Это костыли. Чтобы не было переполнения, можно как минимум раскрыть скобки в выражении `(a+b)/2`

**Comment by levyn** [comment]
a/2 + b/2 = среднее
